name: build

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.19.x, 22.12.x, 24.0.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 22
      uses: actions/setup-node@v4
      with:
        node-version: 22
    - name: install package
      run: |
        npm install -g @angular/cli@20
        npm ci
    - name: Install Playwright browsers
      run: npx playwright install --with-deps chromium
    - name: run tests
      run: |
        ./run-tests.sh

      env:
        CI: true
